// Code generated by MCHP Chatbot
/**
  Generated Main Source File

  Company:
    Microchip Technology Inc.

  File Name:
    main.c

  Summary:
    This is the main file generated using PIC10 / PIC12 / PIC16 / PIC18 MCUs

  Description:
    This header file provides implementations for driver APIs for all modules
  selected in the GUI. Generation Information : Product Revision  :  PIC10 /
  PIC12 / PIC16 / PIC18 MCUs - 1.81.8 Device            :  PIC16F1936 Driver
  Version    :  2.00
 */

// 20260512 tundra_crc8_V01 CS:4E5C
//LED1:POS
//LED2:DRL
//LED3:LoBeam
//LED4:HiBeam
//LED5:turnLight_L
//LED6:turnLight_R

//20260514 tundra_crc8_V02 CS:F675
//將ECCP3_CallBack函式，獨立成receiver_PWM.c，並重構。

#include "mcc_generated_files/mcc.h"
#include "DATA_define.h"
#include "tundra_crc8.h"
#include "Receiver_PWM.h"

//全域變數定義
bool fFrame_OK = 0;
uint8_t step = 0;
uint8_t crc = 0;
bool fCRC_OK = 0;

flag_D2 D2;
flag_D3 D3;
// flag_CS_index csFlag;
DATA_FRAME rx_data = {.buf = {0}};

uint16_t T10MS_CNT = 0; // 單位:10ms
bool fSignalFail=0;

void LED_output(void)
{

  // CRC檢查
  if (fCRC_OK==0)  
    return;

  // POS
  if (D2.RunLight == 1)
  {
    LED1 = 1;
  }
  else
  {
    LED1 = 0;
  }
  // DRL
  if (D2.DRL == 1)
  {
    LED2 = 1;
  }
  else
  {
    LED2 = 0;
  }
  // HIBEAM
  if (D2.LoBeam == 1)
  {
    LED3 = 1;
  }
  else
  {
    LED3 = 0;
  }
  // LOBEAM
  if (D2.HiBeam == 1)
  {
    LED4 = 1;
  }
  else
  {
    LED4 = 0;
  }
  // 左方向
  if (D3.turnLight_L == 1)
  {
    LED5 = 1;
  }
  else
  {
    LED5 = 0;
  }

  // 右方向
  if (D3.turnLight_R == 1)
  {
    LED6 = 1;
  }
  else
  {
    LED6 = 0;
  }

  for (uint8_t i = 0; i < buf_length; i++)
  {
    rx_data.buf[i] = 0; // 清除資料緩衝區
  }
}

void check_CRC8(void)
{
  if(fFrame_OK==0) return;
  fFrame_OK=0;

  fCRC_OK = 0; // 預設 CRC 檢查失敗
  crc = calculate_crc8(rx_data.data, data_length);
  if(rx_data.crc != crc)
    return; // CRC檢查失敗

  fCRC_OK = 1; // CRC檢查成功
  fSignalFail = 0;
  T10MS_CNT = 0; // 重置信號失效計數器

  D2.Byte = rx_data.buf[2];
  D3.Byte = rx_data.buf[3];
}

void Receiver_FrameData(void)
{
  if (byte_ready == 0) return;
    byte_ready = 0;

    switch (step)
    {
    case 0:
      if (rx_buf == 0xC8)
      {
        // step = 1;
        rx_data.buf[step++] = rx_buf;
      }
      else
      {
        step = 0;
      }
      break;
    case 1:
      if (rx_buf == 0x8B)
      {
        rx_data.buf[step++] = rx_buf;
        // step = 2;
      }
      else
      {
        step = 0;
      }
      break;
    case 2:
      rx_data.buf[step++] = rx_buf;
      // step = 3;
      break;
    case 3:
      rx_data.buf[step++] = rx_buf;
      // step = 4;
      break;
    case 4:
      rx_data.buf[step++] = rx_buf;
      // step = 5;
      break;
    case 5:
      rx_data.buf[step++] = rx_buf;
      // step = 6;
      break;
    case 6:
      rx_data.buf[step++] = rx_buf;
      // step = 7;
      break;
    case 7:
      rx_data.buf[step++] = rx_buf;
      // step = 8;
      break;
    case 8:
      rx_data.buf[step++] = rx_buf;
      // step = 9;
      break;
    case 9:
      rx_data.buf[step++] = rx_buf;
      // step = 10;
      break;
    case 10:
      rx_data.buf[step++] = rx_buf;
      fFrame_OK = 1;
      step = 0;
      break;
    default:
      step = 0;
      break;
    }
}


void TMR0_EvenHandler(void)
{
  T10MS_CNT++;
  if (T10MS_CNT >= 200)
  {                  // 2000ms
    T10MS_CNT = 0;
    fSignalFail = 1; // 信號失效
  }
}

void CheckSignalFail(void)
{
  if (fSignalFail == 1)
  {
    fSignalFail = 0;
    // 信號失效處理 亮近燈和POS
    LED1=1;
    LED2=0;
    LED3=1;
    LED4=0;
    LED5=0;
    LED6=0;
  }
}

/*
                         Main application
 */
int main(void)
{
  // initialize the device
  SYSTEM_Initialize();
  TMR0_SetInterruptHandler(TMR0_EvenHandler);

  // When using interrupts, you need to set the Global and Peripheral
  // Interrupt Enable bits Use the following macros to:

  // Enable the Global Interrupts
  INTERRUPT_GlobalInterruptEnable();

  // Enable the Peripheral Interrupts
  INTERRUPT_PeripheralInterruptEnable();

  while (1)
  {
    Receiver_FrameData();
    check_CRC8();
    LED_output();
    CheckSignalFail();
  }
  return 0;
}

/**
 End of File
 */